### ISSUE TITLE
Provide a yml example - further config

### ISSUE THREAD

**Issue by derTobsch** [JasonEtco/upload-to-release#8]
Is there a yml example somewhere? And how could I parameters like `prerelease`, `body` and more of these?

**Comment by JasonEtco** [comment]
Hello! This actions has not been updated to work with Actions v2. It should work just fine, but I haven't invested the time to update the examples yet.

For `prerelease/body`, etc, note that this action is specifically built to _upload_ a file to an _existing_ release; it sounds like you're asking about creating the release, which is not something that this action does.

**Comment by derTobsch** [comment]
Thanks for your reply. It this the way, only upload releases, this actions should be developed? Or should it, somewhere in the future, provide all upload functionality of a release?

**Comment by JasonEtco** [comment]
That's a good question - it's a matter of opinion really, I don't think there's one right answer. I'd say that because actions _can_ be isolated and focused, they should be, so that they can be composed by workflows. Its similar to how the JavaScript ecosystem makes use of many small libraries that come together to create an application. By that's just my opinion 😊 

I'll say that I have no plans to add features to this action; creating a release is a whole 'nother problem space, and there are already tools that existing that do it really well. Hope that answers your question!

I'm going to close this issue since there are no action items, but I appreciate the discussion 😄
